# Use Alpine Linux as base image
FROM python:3.9-alpine

# Set working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install necessary dependencies
RUN apk add --no-cache nmap && \
    pip install python-telegram-bot

# Expose the port the bot runs on
EXPOSE 8443

# Run the bot
CMD ["python", "telegram_port_monitor_bot.py"]
