#!/bin/bash

# Specify the disk you want to partition (change accordingly)
disk="/dev/sdX"

# Calculate the size of each partition in megabytes (100GB)
partition_size_mb=102400

# Start parted in interactive mode for the specified disk
parted -s "$disk" mklabel gpt

# Create partitions
for ((i = 1; i <= 8; i++)); do
    # Calculate the start position for each partition
    start_position=$((($i - 1) * $partition_size_mb))
    
    # Calculate the end position for each partition
    end_position=$(($start_position + $partition_size_mb))

    # Create partition
    parted -s "$disk" mkpart primary ext4 "${start_position}MB" "${end_position}MB"

    # Format partition with ext4 filesystem
    mkfs.ext4 "${disk}""$i"
done
